profiles:
  internal:
    camera_id: 0
    frame_rate: 30.0
    image_width: 640
    image_height: 480
    fourcc: MJPG
    frame_id: internal_camera_optical_frame
    camera_info_url: "package://nebula_vision/calib/internal.yaml"
